### ISSUE TITLE
Unable to connect to --notls btcd

### ISSUE THREAD

**Issue by stevenroose** [conformal/btcwallet#157]
In order to use btcd for BFLMiner, I had to turn off TLS for btcd using the `--notls` flag.

However, btcwallet does not support this flag and seems unable to connect to an HTTP `rpcconnect`.

**Comment by davecgh** [comment]
Good point.  The `--notls` flag is a recent addition to btcd and wallet hasn't been updated to allow it yet.

**Comment by davecgh** [comment]
I've asked @tuxcanfly to take a look at this.  Something pertinent is that wallet is both an RPC server itself and also talks to btcd, so a simple `--notls` flag would be unclear which piece it's referring to.

**Comment by stevenroose** [comment]
btcwallet <-> btcgui connection can be HTTPS while btcd <-> btcwallet is not.

Actually, the better option would be to fix BFLMiner with TLS enabled, but I did not succeed with that.

As for the `--notls` confusion, I'd suggest to allow protocol inclusion in the `rpcconnect` param. Currently, if I enter `rpcconnect=http://localhost:port` instead of the default `rpcconnect=localhost`, it will still try to use HTTPS, ignoring the protocol in the parameter.

**Comment by tuxcanfly** [comment]
Quoting the help page:

`rpcconnect - Hostname/IP and port of btcd RPC server to connect to`

So we are not expecting the protocol in the param. Keeping the TLS options consistent, I think it would be better to have another config param to disable TLS between btcwallet and btcd.

**Comment by davecgh** [comment]
This has been fixed by #158.

**Comment by stevenroose** [comment]
You guys are amazing! Never had such rapid responses to issues with open source software!

**Comment by stevenroose** [comment]
I don't know if this has to do with the recent change here, but I recently setup btcwallet with `noclienttls=1; noservertls=0` and when I try run btcgui, I get a lot of these error messages in btcwallet (even though everything seems to run fine):
```
2015/01/23 22:39:30 http: TLS handshake error from 127.0.0.1:37001: tls: oversized record received with length 21536
2015/01/23 22:39:31 http: TLS handshake error from 127.0.0.1:37002: tls: no cipher suite supported by both client and server
```
btcgui does not support `notls` so I have to enable server TLS for btcwallet, but I also need to have btcd's TLS turned of for the miner.

FYI, if I set `noservertls=1`, I get this message in btcgui, as expected:
```
2015/01/23 22:44:59 [ERR] cannot create websocket config: tls: oversized record received with length 20527
```

**Comment by davecgh** [comment]
I'm pretty sure the `noservertls=0` entry doesn't disable it, rather it sees `nosevertls` and enables it.  Comment out the line instead.  I'm going to add some informational prints when TLS is disabled to wallet here in a moment, since that seems like useful information to display.

**Comment by stevenroose** [comment]
Ow, noticed something weird. The errors keep coming when I shut down btcgui. So they come from somewhere else. No idea from where though... I got a bunch of them every few seconds.

**Comment by stevenroose** [comment]
Ok, it seems to be BFLMiner wanting to connect to port 8332 for no reason. Probably it stored the location from when I ran bitcoind. So nevermind, weird stuff's gone :)

**Comment by davecgh** [comment]
Pull request #177 adds info prints when client/server TLS is disabled.

**Comment by davecgh** [comment]
@stevenroose: Ah that makes sense.  Also, I was wrong as it does appear that `noservertls=0` in the config file disables it as expected.
